services:
  app:
    build: .
    expose:
      - "3000"
      - "3001"

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app
